#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
(
  echo "\n ✅ - Dependencies successfully updated, now linting code..\n"
  true;
) &&

npm run lint ||
(
  echo "\n ❌ - yarn lint Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Code successfully linted, now applying default formatting to the code.. \n"
  true;
) &&

modified_files=$(git status --porcelain | awk '$1 == "M" || $1 == "MM" {print $2}')

git add $modified_files ||
(
  echo "\n ❌ - git add Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Formatted files successfully added to git, now compiling Typescript..\n"
  true;
) &&

npx tsc ||
(
  echo "\n ❌ - npx tsc Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "\n ✅ - Typescript successfully compiled. I am now committing this! - 🚀🔥\n"
  true;
)
