#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint ||
(
  echo "❌ - npm run lint Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "✅ - Code successfully linted, now applying default formatting to the code.. \n"
  true;
) &&

modified_files=$(git status --porcelain | awk '$1 == "M" || $1 == "MM" {print $2}')

git add $modified_files ||
(
  echo "❌ - git add Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "✅ - Formatted files successfully added to git, now compiling Typescript..\n"
  true;
) &&

npx tsc ||
(
  echo "❌ - npx tsc Failed. - ❌\n View the errors above in order to fix them!\n"
  false;
)

(
  echo "✅ - Typescript successfully compiled. I am now committing this! - 🚀🔥\n"
  true;
)
